# Generated by Django 6.0 on 2025-12-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_tbl_adminregistration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_adminregistration',
        ),
    ]
