# Generated by Django 6.0 on 2026-01-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicletype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicletype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
