# Generated by Django 6.0 on 2026-01-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_localplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_employee',
            name='employee_salary',
            field=models.IntegerField(),
        ),
    ]
