# Generated by Django 6.0 on 2026-01-07 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0014_tbl_localplace'),
        ('Guest', '0010_alter_tbl_driver_driver_doj'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=50)),
                ('vehicle_details', models.CharField(max_length=30)),
                ('vehicle_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('vehicle_baseprice', models.IntegerField()),
                ('vehicle_kmprice', models.IntegerField()),
                ('vehicle_status', models.IntegerField(default=0)),
                ('vehicle_capasity', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_model')),
            ],
        ),
    ]
