# Generated by Django 6.0 on 2026-01-07 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_vehicle',
        ),
    ]
