# Generated by Django 6.0 on 2025-12-29 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_seller',
        ),
    ]
