# Generated by Django 6.0 on 2026-01-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_vehicletype'),
        ('Guest', '0008_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_email', models.CharField(max_length=30)),
                ('driver_contact', models.CharField(max_length=15)),
                ('driver_address', models.CharField(max_length=30)),
                ('driver_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('driver_license', models.FileField(upload_to='Assets/UserDocs/')),
                ('driver_password', models.CharField(max_length=30)),
                ('driver_status', models.IntegerField(default=0)),
                ('driver_doj', models.DateField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
