# Generated by Django 6.0 on 2026-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_driver',
            name='driver_doj',
            field=models.DateField(auto_now_add=True),
        ),
    ]
