# Generated by Django 6.0 on 2026-02-02 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_tbl_driver_driver_doj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_status',
        ),
    ]
