# Generated by Django 6.0 on 2026-01-08 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_tbl_employee_employee_salary'),
        ('Driver', '0003_initial'),
        ('Guest', '0010_alter_tbl_driver_driver_doj'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_amount', models.IntegerField()),
                ('booking_todate', models.DateField()),
                ('fromlocalplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='Admin.tbl_localplace')),
                ('tolocalplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='Admin.tbl_localplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.tbl_vehicle')),
            ],
        ),
    ]
