# Generated by Django 6.0 on 2026-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.IntegerField(null=True),
        ),
    ]
