# Generated by Django 6.0 on 2026-01-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_tbl_booking_booking_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
