# Generated by Django 6.0 on 2026-01-14 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaints',
            old_name='complaint_replay',
            new_name='complaint_reply',
        ),
    ]
