# Generated by Django 6.0 on 2026-01-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_complaint_replay_tbl_complaints_complaint_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
