# Generated by Django 6.0 on 2026-01-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_delete_tbl_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_complaint',
            old_name='complaint_replay',
            new_name='complaint_reply',
        ),
    ]
