# Generated by Django 6.0 on 2026-01-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='bookinguser_status',
            field=models.IntegerField(default=0),
        ),
    ]
