# Generated by Django 6.0 on 2026-01-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_booking_bookinguser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaints',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_complaints',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
