# Generated by Django 6.0 on 2026-02-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_booking_tbl_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_fromdate',
            field=models.DateField(null=True),
        ),
    ]
