# Generated by Django 6.0 on 2026-02-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_tbl_employee_employee_salary'),
        ('User', '0016_tbl_booking_booking_fromdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_booking',
            name='booking_distance',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='fromlocalplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_place', to='Admin.tbl_localplace'),
        ),
        migrations.AlterField(
            model_name='tbl_booking',
            name='tolocalplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_place', to='Admin.tbl_localplace'),
        ),
    ]
