# Generated by Django 6.0 on 2026-02-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_booking_booking_advance_tbl_booking_booking_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaints',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_complaints',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_complaints',
        ),
    ]
