# Generated by Django 6.0 on 2026-02-10 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0003_initial'),
        ('Guest', '0011_remove_tbl_user_user_status'),
        ('User', '0018_remove_tbl_complaints_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default=0)),
                ('bookinguser_status', models.IntegerField(default=0)),
                ('booking_amount', models.IntegerField(null=True)),
                ('booking_advance', models.IntegerField(null=True)),
                ('booking_days', models.IntegerField(null=True)),
                ('booking_distance', models.CharField(max_length=50, null=True)),
                ('booking_fromdate', models.DateField(null=True)),
                ('booking_todate', models.DateField()),
                ('booking_fromplace', models.CharField(max_length=200, null=True)),
                ('booking_toplace', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Driver.tbl_vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=50)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=50, null=True)),
                ('complaint_status', models.IntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
