# Generated by Django 6.0 on 2026-02-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_remove_tbl_user_user_status'),
        ('User', '0019_tbl_booking_tbl_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_datetime', models.DateField(auto_now_add=True)),
                ('rating_content', models.CharField(max_length=60)),
                ('rating_value', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
